import { Injectable, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class MaintenanceService {
  constructor(private prisma: PrismaService) {}

  // Preventive Maintenance Engine Trigger (Biasanya di panggil via Cron Job)
  async triggerPreventiveMaintenance(companyId: string) {
    const today = new Date();
    
    // Cari jadwal yang tanggal berikutnya (next_schedule) kurang dari sama dengan hari ini
    const dueSchedules = await this.prisma.maintenanceSchedule.findMany({
      where: {
        asset: { company_id: companyId },
        status: 'ACTIVE',
        next_schedule: { lte: today },
      },
      include: { asset: true }
    });

    const createdWorkOrders: any[] = [];

    for (const schedule of dueSchedules) {
      await this.prisma.$transaction(async (tx) => {
        // Create Work Order
        const wo = await tx.workOrder.create({
          data: {
            asset_id: schedule.asset_id,
            wo_number: `WO-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
            title: `Preventive Maintenance - ${schedule.asset.asset_name}`,
            maintenance_type: 'Preventive',
            priority: 'HIGH',
            status: 'OPEN',
            created_by: 'SYSTEM', // Generated by Cron
          }
        });

        // Update schedule for the next interval
        // Logika sederhana penambahan interval waktu (misal interval_type = DAYS)
        let nextDate = new Date(schedule.next_schedule);
        if (schedule.interval_type === 'DAYS') {
          nextDate.setDate(nextDate.getDate() + schedule.interval_value);
        } else if (schedule.interval_type === 'MONTHS') {
          nextDate.setMonth(nextDate.getMonth() + schedule.interval_value);
        } // Logika lainnya (Usage_Hours / KM) perlu integrasi log terpisah

        await tx.maintenanceSchedule.update({
          where: { id: schedule.id },
          data: {
            last_schedule: new Date(), // Triggered date
            next_schedule: nextDate,
          }
        });

        // History
        await tx.assetHistory.create({
          data: {
            asset_id: schedule.asset_id,
            action: 'PREVENTIVE_WO_CREATED',
            after_data: wo as any,
            performed_by: 'SYSTEM',
          }
        });

        createdWorkOrders.push(wo);
      });
    }

    return createdWorkOrders;
  }
}
